### ISSUE TITLE
Heretic Unchained cannot be revived

### ISSUE THREAD

**Issue by SOMSTATE** [KosmosisDire/TeammateRevive#12]
Heretic shatters upon death, so they do not create a grave.

**Comment by KosmosisDire** [comment]
So I just talked to the creator of HereticUnchained, and I don't think it's a problem with their mod, but rather a problem with just the vanilla Heretic survivor. Could you test this without the HereticUnchained mod, and see if it still doesn't work with the vanilla survivor? Also could you check (if you can) if this also happens when a survivor dies while holding shaped glass?

**Comment by KosmosisDire** [comment]
Actually, I am pretty sure that it is just the vanilla survivor, but it would be nice if you could still test the shaped glass if you get the chance. I will also try to test it if I can, and try to find a solution. Thanks for reporting, and let me know what you find!

**Comment by KosmosisDire** [comment]
(deleted my other comments to relieve clutter). I think I've figured out the problem and I'll try to find a fix. It is kind of complicated though so it might take a while. Thanks for reporting this!

**Comment by KosmosisDire** [comment]
Closing as this probably won't be fixed by me.
