### ISSUE TITLE
Floating Skull and lack of skulls afterwards (ver. 3.3.5)

### ISSUE THREAD

**Issue by spindocks** [KosmosisDire/TeammateRevive#9]
Tested the new version and it did work, but...
![20210727001855_1](https://user-images.githubusercontent.com/80333274/127099085-4022bb52-a08a-4248-9ccf-5293883b9f81.jpg)
I think the skulls being stuck in air has returned. Also, does this work in void fields? It was bugged out.
[335.txt](https://github.com/KosmosisDire/TeammateRevive/files/6882844/335.txt)
[log.txt](https://github.com/KosmosisDire/TeammateRevive/files/6882860/log.txt)

**Comment by spindocks** [comment]
I tested with just a friend and the skull spawned and everything, however after awhile it stopped working again when playing a legitimate game. The one time it worked was when my friend died over the ledge, causing the skull to spawn there. Afterwards it wouldn't spawn properly.

**Comment by KosmosisDire** [comment]
So I think that the drop in multiplayer might have something to do with this. It looks like He got added three times which means that my mod thought there were three of him. So it never finished setting up all the players. I actually had another group tell me about this same problem but I am not sure if they were using drop-in multiplayer. I'll check it out and let you know if I have any more questions. Thanks!

**Comment by KosmosisDire** [comment]
And as far as I know it should work in void fields. What was it doing differently in void fields?

**Comment by spindocks** [comment]
> And as far as I know it should work in void fields. What was it doing differently in void fields?

It might have been the fact that dropinmultiplayer happened but all of the people who died, the game would say that they died across the map (no skull)

**Comment by KosmosisDire** [comment]
I just pushed a new update that should at least fix the problem with drop in multiplayer. Hopefully that was the only problem and it will work now, but we'll see

**Comment by spindocks** [comment]
Checking the last issue on mid-air deaths has me wondering: with the ray-cast downwards, what if there is no ground downwards? Has this already been addressed? I don't know what caused that death I showed; my friend claims they were much farther away from where the skull actually placed. However, in the event that they did actually die over a pit would it cast the skull onto the closest land?

**Comment by KosmosisDire** [comment]
Yes I have a system so that it only keeps that last valid ground position. and it will only register a new position if it is closer to the player than the last one. So if you jump of a cliff the last ground position that was underneath the player would be on the edge of the cliff before they jumped. Or if they jump off a cliff into the ground below the last position will still be on the edge of the cliff until they have fallen halfway to the ground at which point the ground position will switch to the ground beneath. I have tested this extensively and I know it works.

My theory is that because the player list was getting messed up Its possible that the ground position wasn't being updated correctly and just got "frozen" at some point. So it just spawned at a position that the player was at in some past time or level. I don't know though. It's also possible something has gone wrong with my system in the last few updates so I'll test it again just to be sure.

**Comment by Buzing** [comment]
Hi! Im also having this issue, but on 3.3.6, I am guessing it happens due to us having more than 4 players. but this is unconfirmed. 

same thing happens. Floating head then no more skulls afterwards, I can try to look for logs if possible, or even invite you to play :) !@

**Comment by KosmosisDire** [comment]
Hmmm... Maybe I should just revert back to 3.1.1 and redo all the other stuff. Cause I think I just messed it up and can't find what's wrong. Let me know what you find though!

**Comment by KosmosisDire** [comment]
Okay actually I may have found the bug! Give the latest version a try and let me know how it goes! @Buzing @spindocks

**Comment by Bitr0t-Zygzz** [comment]
Its pretty funny seeing the quick turn around from negative to positive :) ! haha 

anyway ill go test it out with my friends later. Thank you for your hard work o/

**Comment by Bitr0t-Zygzz** [comment]
Issue is fixed! but it introduces a new bug with people reviving by themselves, (its still fun but might be game breaking for some). I will put more details on another post. Still haven't tried more than 4 players but its working great with 4!

**Comment by KosmosisDire** [comment]
Okay so looks like this issue is closed
